# 1. PersistentVolume y PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-python-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks
    type: DirectoryOrCreate
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-python-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: simple-python-pv

---
# 2. Deployment de la aplicación Python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: python-app
          image: diegoayi/simple-python-app:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: simple-python-pvc

---
# 3. Service para la aplicación Python
apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Expuesto fuera del clúster (puedes usar LoadBalancer si lo tienes disponible)
