apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: python-app
          image: diegoayi/simple-python-app:latest  # Asegúrate de que la imagen sea la correcta
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"  # Asegúrate de que Flask esté en desarrollo para logs detallados
---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80  # El puerto por el que se expondrá el servicio
      targetPort: 5000  # El puerto interno en el que la aplicación Flask está escuchando
