apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: python-app
          image: diegoayi/simple-python-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  type: NodePort  # Cambiado para que puedas acceder desde fuera del clúster (opcional)
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Puerto fijo (puede estar entre 30000-32767), o dejá que se asigne automáticamente
