---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-python-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/python-app  # Ruta en el nodo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-python-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: python-app
          image: diegoayi/simple-python-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: simple-python-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  type: LoadBalancer
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
