apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-python-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks
    type: DirectoryOrCreate
  storageClassName: standard
