apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: python-app
          image: diegoayi/simple-python-app:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: simple-python-pvc
